"""
Data Warehouse connector — read-only PostgreSQL analytics database.
Executes pre-validated SELECT queries generated by the NL2SQL translator.
"""

# asyncpg is a native async PostgreSQL driver — zero blocking, no thread wrappers
import asyncpg

# os reads the DWH connection URL from the environment
import os

# type hints for function parameters and return values
from typing import Any, Dict, List, Optional

# shared structured logger tagged "DB_AGENT" on every line
from shared.communication_layer.logger import get_logger

# creates the module logger instance
logger = get_logger("DB_AGENT")

# reads the DWH PostgreSQL DSN from the environment
# expected format: postgresql://user:password@host:5432/dwh
DWH_URL = os.getenv("DWH_URL", "")

# module-level pool — None until first use, then shared for the process lifetime
_pool: Optional[asyncpg.Pool] = None


async def _get_pool() -> asyncpg.Pool:
    """Creates the DWH connection pool on first call, then returns the cached pool."""

    # tell Python we assign to the module variable, not a new local
    global _pool

    # only create the pool once
    if _pool is None:

        # open the pool — min_size connections are dialled immediately
        _pool = await asyncpg.create_pool(
            # the DWH connection string from .env
            dsn=DWH_URL,
            # always keep 1 connection warm — DWH queries are less frequent than OLTP
            min_size=1,
            # cap at 5 — DWH is read-only and lower throughput than legacy_db
            max_size=5,
        )

        # log pool creation for operator visibility
        logger.info("dwh_pool_created")

    # return the pool (cached or freshly created)
    return _pool


class DWHConnector:
    """Executes pre-validated SELECT queries against the read-only Data Warehouse."""

    async def execute_query(
        self,
        # the SQL string — must already be validated as safe before calling this method
        sql: str,
        # optional list of bind-parameter values, bound positionally ($1, $2, ...)
        params: List[Any] = [],
    ) -> List[Dict[str, Any]]:
        """Executes a safe, pre-validated SELECT query. Returns rows as a list of dicts."""

        # get the shared DWH pool
        pool = await _get_pool()

        # log the outgoing query for audit and debugging — do NOT log params (may contain PII)
        logger.info("dwh_query_executing")

        # borrow one connection from the pool for the duration of the query
        async with pool.acquire() as conn:

            # *params unpacks the list into positional arguments for asyncpg
            # asyncpg binds them as $1, $2, ... — never formats them into the SQL string
            rows = await conn.fetch(sql, *params)

        # convert every asyncpg Record to a plain Python dict
        results = [dict(row) for row in rows]

        # log how many rows were returned — useful for detecting runaway queries
        logger.info("dwh_query_done", row_count=len(results))

        # return the list of dicts — empty list if no rows matched
        return results
