name: BIAS CD

on:
  push:
    branches: [main]
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - orchestrator
          - communicator
          - db-agent
          - llm-agent
          - file-management
          - claims-expert
          - chatbot
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t bias-${{ matrix.service }}:${{ github.sha }} \
            ./${{ matrix.service }}/
